panes:
  - command: <agent> # Start the configured agent (e.g., claude)
    focus: true
  - split: horizontal # Second pane with default shell

# Commands run after worktree creation (blocks window creation, keep fast)
files:
  symlink:
    - CLAUDE.md
    - tests/venv # Share Python venv for faster worktree creation

pre_merge: just check
